development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://wcwevxduguvije:dcce0b1a0abca5e5cefb0eba927cced150280429d647f9682260d8e03776ef3f@ec2-54-225-230-243.compute-1.amazonaws.com:5432/d2be4t2i1vdrf3
